- name: Create directory to hold uncompressed software sources
  file: dest=~/software state=directory

- name: Create directory to hold compressed software sources
  file: dest=~/compressed state=directory

- name: Download zsh sources
  get_url: url=http://sourceforge.net/projects/zsh/files/zsh/5.0.7/zsh-5.0.7.tar.gz/download dest=~/compressed/zsh-5.0.7.tar.gz sha256sum=43f0a4c179ef79bb8c9153575685f7f45f28a3615c8cf96345f503d5b9e7b919

- name: Extract zsh sources
  shell: tar xvf ~/compressed/zsh-5.0.7.tar.gz -C ~/software/ creates=~/software/zsh-5.0.7

- name: Install zsh
  shell: cd {{ ansible_env["HOME"] }}/software/zsh-5.0.7/ && ./configure --prefix=/usr/local && make && make install creates=/usr/local/bin/zsh
  sudo: yes

- name: Enable installed zsh shell
  shell: grep -q -F "/usr/local/bin/zsh" /etc/shells || printf "/usr/local/bin/zsh" >> /etc/shells
  sudo: yes

- name: Set zsh as the user shell
  user: name=iqbal shell=/usr/local/bin/zsh

- name: Checkout autojump
  git: repo=git://github.com/joelthelion/autojump.git dest=~/software/autojump depth=1 accept_hostkey=True

- name: Install autojump using the installation script
  shell: cd ~/software/autojump && ./install.py -p ~/local_packages creates=/home/iqbal/local_packages/bin/autojump

- name: Enable autojump in zsh
  shell: grep -q -F "{{ autojump.config }}" ~/.zshrc || printf "\n{{ autojump.config }}" >> ~/.zshrc
