- hosts: localhost

  environment:
    PATH: "{{lookup('env', 'HOME')}}/.local/bin/:{{lookup('env', 'PATH')}}"

  vars_files:
    - variables.yaml

  tasks:
    - import_tasks: apps/common.yaml
    - import_tasks: apps/zsh.yaml
    - import_tasks: apps/less.yaml
    - import_tasks: apps/tmux.yaml
    - import_tasks: apps/emacs.yaml
    - import_tasks: apps/git.yaml
    - import_tasks: apps/browsers.yaml
    - import_tasks: apps/st.yaml
    - import_tasks: apps/gnome-terminal.yaml
    - import_tasks: apps/iterm2.yaml
    - import_tasks: apps/gtk.yaml
    - import_tasks: apps/rofi.yaml
    - import_tasks: apps/dunst.yaml
    - import_tasks: apps/terminal-notifier.yaml
    - import_tasks: apps/gnome-panel.yaml
    - import_tasks: apps/kde-connect.yaml
    - import_tasks: apps/xmonad.yaml
    - import_tasks: apps/ledger.yaml
    - import_tasks: apps/zathura.yaml
    - import_tasks: apps/alfred.yaml
    - import_tasks: apps/spectacle.yaml
    - import_tasks: apps/karabiner.yaml
    - import_tasks: apps/fonts.yaml
    - import_tasks: apps/mail.yaml
    - import_tasks: apps/vagrant.yaml
    - import_tasks: apps/virtualbox.yaml
    - import_tasks: apps/artha.yaml
    - import_tasks: apps/misc.yaml
      # Tasks to setup language environments
    - import_tasks: langs/factor.yaml
    - import_tasks: langs/c.yaml
