- hosts: localhost

  environment:
    PATH: "{{lookup('env', 'HOME')}}/.local/bin/:{{lookup('env', 'PATH')}}"

  vars_files:
    - variables.yaml

  tasks:
    - import_tasks: tasks/common.yaml
    - import_tasks: tasks/zsh.yaml
    - import_tasks: tasks/less.yaml
    - import_tasks: tasks/tmux.yaml
    - import_tasks: tasks/emacs.yaml
    - import_tasks: tasks/git.yaml
    - import_tasks: tasks/browsers.yaml
    - import_tasks: tasks/st.yaml
    - import_tasks: tasks/gnome-terminal.yaml
    - import_tasks: tasks/iterm2.yaml
    - import_tasks: tasks/gtk.yaml
    - import_tasks: tasks/rofi.yaml
    - import_tasks: tasks/dunst.yaml
    - import_tasks: tasks/terminal-notifier.yaml
    - import_tasks: tasks/gnome-panel.yaml
    - import_tasks: tasks/kde-connect.yaml
    - import_tasks: tasks/xmonad.yaml
    - import_tasks: tasks/zathura.yaml
    - import_tasks: tasks/alfred.yaml
    - import_tasks: tasks/spectacle.yaml
    - import_tasks: tasks/karabiner.yaml
    - import_tasks: tasks/fonts.yaml
    - import_tasks: tasks/mail.yaml
    - import_tasks: tasks/vagrant.yaml
    - import_tasks: tasks/virtualbox.yaml
    - import_tasks: tasks/artha.yaml
    - import_tasks: tasks/misc.yaml
