- name: Install and configure Gnome Panel
  block:
    - name: Install gnome-panel and indicators
      apt: pkg={{ item }} update_cache=yes cache_valid_time=604800 install_recommends=no
      with_items:
        - gnome-panel
        - gnome-applets
        - gnome-applets-data
        - indicator-applet
        - indicator-datetime
        - indicator-power
        - indicator-session
        - indicator-applet-session
        - indicator-applet-complete

      tags:
        - provision

    - name: Configure gnome-panel to match Tomorrow Night theme
      dconf: key=/org/gnome/gnome-panel/{{item.key}} value={{item.value}} state=present
      with_dict:
        layout/toplevels/top-panel/size: 28
        layout/toplevels/top-panel/theme/custom-bg-color: 'true'
        layout/toplevels/top-panel/theme/custom-fg-color: 'true'
        layout/toplevels/top-panel/theme/bg-color: "'rgb(29,31,33)'"
        layout/toplevels/top-panel/theme/fg-color: "'rgb(197,200,198)'"
        layout/toplevels/bottom-panel/theme/custom-bg-color: 'true'
        layout/toplevels/bottom-panel/theme/custom-fg-color: 'true'
        layout/toplevels/bottom-panel/theme/bg-color: "'rgb(29,31,33)'"
        layout/toplevels/bottom-panel/theme/fg-color: "'rgb(197,200,198)'"

      tags:
        - configuration

  when: ansible_distribution == 'Ubuntu' and lookup('env', 'DISPLAY')

  tags:
    - gnome-panel
    - xmonad
    - panel
