- name: Configure GTK
  block:
    - name: Change the theme to Adwaita-Dark
      dconf: key='/org/gnome/desktop/interface/gtk-theme' value="'Adwaita-dark'"

    - name: Change icon theme to Humanity-Dark
      dconf: key='/org/gnome/desktop/interface/icon-theme' value="'ubuntu-mono-dark'"

    - name: Change key theme to Emacs
      dconf: key='/org/gnome/desktop/interface/gtk-key-theme' value="'Emacs'"

    - name: Symlink gtk2 configuration
      install_dot: src=files/gtk/gtkrc-2.0 dest=~/.gtkrc-2.0

    - name: Symlink gtk3 configuration
      install_dot: src=files/gtk/gtk-3.0 dest=~/.config/gtk-3.0

  when: ansible_distribution == "Ubuntu" and lookup('env', 'DISPLAY')

  tags:
    - gtk
    - configuration
