- name: Install and configure Karabiner
  block:
    - name: Install Karabiner
      homebrew_cask: name=karabiner-elements
      tags:
        - provision

    - name: Symlink Karabiner configuration
      install_dot: src=files/karabiner dest='~/.config/karabiner'
      tags:
        - configuration

  when: ansible_distribution == "MacOSX"

  tags:
    - karabiner
