- name: Install lesspipe
  block:
    - name: Get lesspipe
      git: repo=https://github.com/wofr06/lesspipe accept_hostkey=yes dest=~/software/lesspipe version={{lesspipe_version}}
      register: lesspipe_source

    - name: Check if lesspipe is installed
      shell: which lesspipe
      register: lesspipe_installed
      ignore_errors: yes
      failed_when: no
      changed_when: no

    - name: Install lesspipe
      shell: cd ~/software/lesspipe && ./configure --prefix=~/.local/ --yes && make install && git checkout -f
      when: lesspipe_source is changed or lesspipe_installed.rc == 1

  tags:
    - less
    - provision

- name: Install custom less input preprocessor
  install_dot: src=files/less-input-preprocessor.sh path=~/.local/bin/less-input-preprocessor.sh
  tags:
    - less
    - configuration

- name: Install pygments for syntax highlighting in less
  pip: name=pygments
  become: yes
  tags:
    - less
    - provision
