- name: Configure Gnome Terminal
  block:
    - name: Install gconftool
      apt: pkg=gconf2 update_cache=yes cache_valid_time=604800 install_recommends=no
      become: yes

    - name: Checkout base16-gnome-terminal project
      git: repo=https://github.com/chriskempson/base16-gnome-terminal dest=~/software/base16-gnome-terminal depth=1 accept_hostkey=yes update=yes
      register: base16_gnome_terminal

    - name: Install color theme
      command: ~/software/base16-gnome-terminal/base16-tomorrow.dark.sh
      changed_when: no

    - name: Set installed theme as the default theme
      gconftool2: key=/apps/gnome-terminal/global/default_profile value=base-16-tomorrow-dark value_type=string state=present

    - name: Change font
      gconftool2: key=/apps/gnome-terminal/profiles/base-16-tomorrow-dark/font value="Source Code Pro Regular 10" value_type=string state=present

    - name: Do not show the menubar
      dconf: key=/org/gnome/terminal/legacy/default-show-menubar value=false

  when: ansible_distribution == 'Ubuntu' and lookup('env', 'DISPLAY')

  tags:
    - terminal
    - configuration


- name: Install and configure iTerm
  block:
    - name: Install iTerm2
      homebrew_cask: name=iterm2

    - name: Symlink custom profile
      install_dot: src=files/iterm/iterm-custom-profile.json dest='~/Library/Application Support/iTerm2/DynamicProfiles/iterm-custom-profile.json'

    - name: Make the custom profile the default profile
      osx_defaults: domain=com.googlecode.iterm2 key='Default Bookmark Guid' type=string value='D159F1F0-2D8A-4766-9603-E487527862EC'

  when: ansible_distribution == 'MacOSX'

  tags:
    - terminal
