- name: Configure Gnome Terminal
  block:
    - name: Install color theme
      command: files/gnome-terminal/base16-tomorrow-dark-theme.sh
      changed_when: no

    - name: Set installed theme as the default theme
      dconf: key=/org/gnome/terminal/legacy/profiles:/default value='"62f4ee90-5743-478c-af66-c64366b4a452"' state=present

    - name: Change font
      dconf: key=/org/gnome/terminal/legacy/profiles:/:62f4ee90-5743-478c-af66-c64366b4a452/font value='"Source Code Pro Regular 10"' state=present

    - name: Do not show the menubar
      dconf: key=/org/gnome/terminal/legacy/default-show-menubar value=false

  when: ansible_distribution == 'Ubuntu' and lookup('env', 'DISPLAY')

  tags:
    - terminal
    - configuration


- name: Install and configure iTerm
  block:
    - name: Install iTerm2
      homebrew_cask: name=iterm2

    - name: Symlink custom profile
      install_dot: src=files/iterm/iterm-custom-profile.json dest='~/Library/Application Support/iTerm2/DynamicProfiles/iterm-custom-profile.json'

    - name: Make the custom profile the default profile
      osx_defaults: domain=com.googlecode.iterm2 key='Default Bookmark Guid' type=string value='D159F1F0-2D8A-4766-9603-E487527862EC'

  when: ansible_distribution == 'MacOSX'

  tags:
    - terminal
