- name: Install and configure xfce4-notifyd on Ubuntu
  block:
      - name: Install xfce4-notifyd
        block:
          - name: Install xfce4-notifyd
            apt: pkg=xfce4-notifyd update_cache=yes cache_valid_time=604800 install_recommends=no
            become: yes

          - name: Uninstall notify-osd
            apt: pkg=notify-osd state=absent
            become: yes

        tags:
          - provision

      - name: Configure xfce4-notifyd
        block:
          - name: Symlink custom gtk theme
            install_dot: src=files/gtk/theme dest=~/.themes/CustomGTKTheme

          - name: Symlink custom config for xfce4-notifyd
            install_dot: src=files/xfce-notifyd/xfce-perchannel-xml dest=~/.config/xfce4/xfconf/xfce-perchannel-xml

          - name: Reload xfconf
            shell: pkill -HUP xfconfd
            changed_when: no
            failed_when: no
            ignore_errors: yes

        tags:
          - configuration

  when: ansible_distribution == "Ubuntu"
  tags:
    - never
    - xfce-notifyd
    - notifications
