- name: Create directory to hold vagrant deb
  file: path=~/software/vagrant state=directory

- name: Download vagrant deb for 64 bit arch
  get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.3_x86_64.deb dest=~/software/vagrant/vagrant_1.7.3.deb timeout=100000
  when: ansible_architecture == "x86_64"

- name: Download vagrant deb for 32 bit arch
  get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.3_i686.deb dest=~/software/vagrant/vagrant_1.7.3.deb timeout=100000
  when: not ansible_architecture == "x86_64"
