- name: Install bzip2
  apt: pkg=bzip2 update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Download 64 bit Firefox
  get_url: url=https://download.mozilla.org/?product=firefox-37.0.2-SSL&os=linux64&lang=en-US dest=~/compressed/firefox-37.0.2.tar.bz2
  when: ansible_architecture == "x86_64"
  register: firefox_64_download

- name: Download 32 bit Firefox
  get_url: url=https://download.mozilla.org/?product=firefox-37.0.2-SSL&os=linux&lang=en-US dest=~/compressed/firefox-37.0.2.tar.bz2
  when: not ansible_architecture == "x86_64"
  register: firefox_32_download

- name: Extract Firefox
  unarchive: src=~/compressed/firefox-37.0.2.tar.bz2 dest=~/software/
  when: firefox_64_download|changed or firefox_32_download|changed

- name: Symlink Firefox binary to local_packages/bin/
  file: src=~/software/firefox/firefox dest=~/local_packages/bin/firefox state=link

- name: Install w3m
  apt: pkg=w3m state=present update_cache=yes cache_valid_time=604800
  sudo: yes
