- name: Install the prerequisites for emacs
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=604800
  with_items:
    - libxaw7-dev
    - libjpeg-dev
    - libgif-dev
    - libxpm-dev
    - libpng12-dev
    - libtiff4-dev
    - libncurses5-dev
    - libtinfo-dev
    - libglib2.0-dev
    - libgtk2.0-dev
    - libxaw3dxft6
    - librsvg2-dev
    - imagemagick
    - libdbus-1-dev
    - libgconf2-dev
    - libm17n-dev
    - libotf-dev
    - graphicsmagick-libmagick-dev-compat
  sudo: yes

- name: Get sources for emacs 24.5
  get_url: url=http://ftpmirror.gnu.org/emacs/emacs-24.5.tar.gz dest=~/compressed/emacs-24.5.tar.gz timeout=100000 sha256sum=2737a6622fb2d9982e9c47fb6f2fb297bda42674e09db40fc9bcc0db4297c3b6

- name: Extract emacs sources
  shell: tar xvf ~/compressed/emacs-24.5.tar.gz -C ~/software/ creates=~/software/emacs-24.5

- name: Install emacs
  shell: cd ~/software/emacs-24.5 && ./configure --prefix={{ ansible_env["HOME"] }}/local_packages/ && make && make install creates={{ ansible_env["HOME"] }}/local_packages/bin/emacs-24.5

- name: Clone my emacs config
  git: repo=https://github.com/iqbalansari/dotEmacs accept_hostkey=True update=yes dest=~/.emacs.d
