- name: Install tmux dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=604800
  with_items:
    - libevent-dev
    - libncurses5-dev
  sudo: yes

- name: Get sources for tmux 2.0
  get_url: url=http://downloads.sourceforge.net/tmux/tmux-2.0.tar.gz dest=~/compressed/tmux-2.0.tar.gz timeout=100000 sha256sum=795f4b4446b0ea968b9201c25e8c1ef8a6ade710ebca4657dd879c35916ad362

- name: Extract tmux sources
  unarchive: src=~/compressed/tmux-2.0.tar.gz dest=~/software/ creates=~/software/tmux-2.0/
  register: tmux_source

- name: Install tmux
  shell: cd ~/software/tmux-2.0/ && ./configure --prefix={{ ansible_env["HOME"] }}/local_packages/ && make && make install
  when: tmux_source|changed

- name: Install TPM
  git: repo=https://github.com/tmux-plugins/tpm.git depth=1 accept_hostkey=True dest=~/.tmux/plugins/tpm

- name: Copy custom .tmux.conf
  copy: src=.tmux.conf dest=~/.tmux.conf backup=yes

- name: Install curl
  apt: pkg=curl update_cache=yes cache_valid_time=604800
  sudo: yes
  
  # If we are already in tmux simply split the window and run the command
  # Supressed changed, since there is no way to detect if the plugins were
  # installed or simply skipped other than checking directory's mod time
  # which feels an overkill
- name: Install tmux plugins (in a tmux session)
  shell: tmux split-window '~/.tmux/plugins/tpm/scripts/install_plugins.sh'
  when: lookup('env', 'TMUX')
  changed_when: False

  # Otherwise we need to start the server, create a session and then run the shell command
- name: Install tmux plugins (outside a tmux session)
  shell: tmux start-server \; new-session -d \; run-shell 'PATH=~/local_packages/bin:$PATH ~/.tmux/plugins/tpm/scripts/install_plugins.sh'
  when: not lookup('env', 'TMUX') 
  changed_when: False
