- name: Create Xresources.d if it does not exist
  shell: mkdir ~/Xresources.d creates=~/Xresources.d

- name: Symlink UXTerm config
  file: src={{ role_path }}/files/uxterm dest=~/Xresources.d/uxterm state=link
  register: uxterm_config
  
- name: Include UXTerm config in ~/.Xresources
  lineinfile: dest=~/.Xresources line='#include "Xresources.d/uxterm"' create=yes state=present

- name: Reload Xresources if UXTerm config changed
  shell: xrdb -merge ~/.Xresources
  when: uxterm_config|changed and lookup('env', 'DISPLAY')
