- name: Checkout base16-gnome-terminal project
  git: repo=https://github.com/chriskempson/base16-gnome-terminal dest=~/software/base16-gnome-terminal depth=1 accept_hostkey=True
  register: base16_gnome_terminal

- name: Install color theme
  command: ~/software/base16-gnome-terminal/base16-tomorrow.dark.sh
  changed_when: False
  
- name: Set installed theme as the default theme
  command: gconftool-2 -s "/apps/gnome-terminal/global/default_profile" -t string base-16-tomorrow-dark
  changed_when: False

- name: Do not use system font
  command: gconftool-2 -s "/apps/gnome-terminal/profiles/base-16-tomorrow-dark/use_system_font" -t bool false
  changed_when: False

- name: Change font
  command: gconftool-2 -s "/apps/gnome-terminal/profiles/base-16-tomorrow-dark/font" -t string "DejaVu Sans Mono 10"
  changed_when: False
