- name: Install dependencies for URxvt
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800
  with_items:
    - libperl-dev
    - xsel
  sudo: yes

- name: Get latest release of URxvt
  get_url: url=http://dist.schmorp.de/rxvt-unicode/rxvt-unicode-9.21.tar.bz2 dest=~/compressed/rxvt-unicode-9.21.tar.bz2 sha256sum=75270ed72bc5895a64a1d7392bf45a622204192371c3965bd3dd978dc088956b

- name: Extract URxvt source
  unarchive: src=~/compressed/rxvt-unicode-9.21.tar.bz2 dest=~/software/ creates=~/software/rxvt-unicode-9.21
  register: urxvt_source

- name: Install URxvt
  shell: cd {{ ansible_env["HOME"] }}/software/rxvt-unicode-9.21/ && ./configure --prefix=/usr/local && make && make install
  sudo: yes
  when: urxvt_source|changed

- name: Create ~/.urxvt/ext to hold custom extensions
  file: path=~/.urxvt/ext state=directory

- name: Get urxvt-perls
  git: repo=https://github.com/muennich/urxvt-perls.git accept_hostkey=True dest=~/software/urxvt-perls

- name: Symlink urxvt-perls 'clipboard' extension
  file: src=~/software/urxvt-perls/clipboard dest=~/.urxvt/ext/clipboard state=link

- name: Symlink urxvt-perls 'url-select' extension
  file: src=~/software/urxvt-perls/url-select dest=~/.urxvt/ext/url-select state=link

- name: Create Xresources.d if it does not exist
  shell: mkdir ~/Xresources.d creates=~/Xresources.d

- name: Symlink URxvt config
  file: src={{ role_path }}/files/urxvt dest=~/Xresources.d/urxvt state=link
  register: urxvt_config
  
- name: Include URxvt config in ~/.Xresources
  lineinfile: dest=~/.Xresources line='#include "Xresources.d/urxvt"' create=yes state=present

- name: Reload Xresources if URxvt config changed
  shell: xrdb -merge ~/.Xresources
  when: urxvt_config|changed and lookup('env', 'DISPLAY')
