- name: Create directory to hold uncompressed software sources
  file: dest=~/software state=directory

- name: Create directory to hold compressed software sources
  file: dest=~/compressed state=directory

- name: Install make
  apt: pkg=make update_cache=yes cache_valid_time=604800
