- name: Install httpie, a better tool for making HTTP requests from cmd
  pip: name=httpie
  sudo: yes

- name: Install rlwrap
  apt: pkg=rlwrap update_cache=yes cache_valid_time=604800 install_recommends=no
  sudo: yes

# Install vim, better for short edits
- name: Install vim
  apt: pkg=vim update_cache=yes cache_valid_time=604800 install_recommends=no
  sudo: yes

- name: Get sources for cloc 1.62
  get_url: url=http://sourceforge.net/projects/cloc/files/cloc/v1.62/cloc-1.62.tar.gz/download dest=~/compressed/cloc-1.62.tar.gz sha256sum=c4111ef5768b1c2844c0c826988df6f92fbb5aa7452a5005d3a031d68631acb3

- name: Extract cloc sources
  unarchive: src=~/compressed/cloc-1.62.tar.gz dest=~/software creates=~/software/cloc-1.62

- name: Install cloc
  shell: cd ~/software/cloc-1.62/ && make prefix={{ ansible_env["HOME"] }}/local_packages/ install creates={{ ansible_env["HOME"] }}/local_packages/bin/cloc

- name: Install dependencies for building ag
  apt: pkg={{ item }} state=present update_cache=yes install_recommends=no cache_valid_time=604800
  with_items:
    - automake
    - pkg-config
    - libpcre3-dev
    - zlib1g-dev
    - liblzma-dev
  sudo: yes

- name: Get sources for ag 0.29.1
  get_url: url=https://github.com/ggreer/the_silver_searcher/archive/0.29.1.tar.gz dest=~/compressed/the_silver_searcher-0.29.1.tar.gz sha256sum=779eb781751fd3dc07bff3b88f4475ed78eea3fa7b21139d8230d17c31db072a

- name: Extract ag sources
  unarchive: src=~/compressed/the_silver_searcher-0.29.1.tar.gz dest=~/software creates=~/software/the_silver_searcher-0.29.1

- name: Install ag
  shell: cd ~/software/the_silver_searcher-0.29.1/ && ./build.sh && ./configure --prefix={{ ansible_env["HOME"] }}/local_packages/ && make && make install creates={{ ansible_env["HOME"] }}/local_packages/bin/ag

- name: Install curl
  apt: pkg=curl update_cache=yes cache_valid_time=604800 install_recommends=no
  sudo: yes

- name: Install Artha
  apt: pkg=artha update_cache=yes cache_valid_time=604800 state=present install_recommends=no
  sudo: yes

- name: Create ~/.config if does not yet exist
  command: mkdir ~/.config creates=~/.config

- name: Symlink artha config file
  file: src={{ role_path }}/files/artha.conf dest=~/.config/artha.conf state=link force=yes
