- name: Install XMonad
  apt: pkg=xmonad update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Install ghc libraries required for configuring XMonad
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800
  with_items:
    - libghc-xmonad-dev
    - libghc-xmonad-contrib-dev
  sudo: yes

- name: Install gnome-panel
  apt: pkg=gnome-panel update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Create directory to hold xmonad config
  command: mkdir ~/.xmonad creates=~/.xmonad

- name: Copy xmonad personal config
  copy: src=xmonad.hs dest=~/.xmonad/xmonad.hs backup=yes
  register: xmonad_config

- name: Copy xmonad startup hook
  copy: src=startup-hook dest=~/.xmonad/startup-hook backup=yes mode=755

- name: Restart xmonad if config changed and xmonad is running
  shell: xmonad --restart
  when: lookup('env', 'DESKTOP_SESSION').find('xmonad') != -1 and xmonad_config|changed

- name: Recompile xmonad if config changed and xmonad is not running
  shell: xmonad --recompile
  when: lookup('env', 'DESKTOP_SESSION').find('xmonad') == -1 and xmonad_config|changed
