- name: Install XMonad
  apt: pkg=xmonad update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Install ghc libraries required for configuring XMonad
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800
  with_items:
    - libghc-xmonad-dev
    - libghc-xmonad-contrib-dev
  sudo: yes

- name: Install gnome-panel
  apt: pkg=gnome-panel update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Install dependencies for Rofi
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800
  with_items:
    - libxinerama-dev
    - libxft-dev
    - libpango1.0-dev
    - libx11-dev

- name: Get Rofi source code
  git: repo=https://github.com/DaveDavenport/rofi.git depth=1 accept_hostkey=True dest=~/software/rofi
  register: rofi_checkout

- name: Install Rofi
  shell: cd ~/software/rofi && autoreconf -i && mkdir -p build && cd build && ../configure --prefix=$HOME/local_packages/ --disable-i3support && make && make install
  when: rofi_checkout|changed

- name: Create .Xresources.d if it does not exist
  shell: mkdir ~/.Xresources.d creates=~/.Xresources.d

- name: Copy Rofi config
  copy: src=rofi dest=~/.Xresources.d/rofi
  register: rofi_config

- name: Include rofi config in ~/.Xresources
  lineinfile: dest=~/.Xresources line='#include "~/.Xresources.d/rofi"\n' create=yes state=present

- name: Restart rofi if config changed
  shell: kill $(pgrep rofi) ; rofi -key-run mod4+s &
  when: rofi_config|changed

- name: Create directory to hold XMonad config
  command: mkdir ~/.xmonad creates=~/.xmonad

- name: Copy XMonad personal config
  copy: src=xmonad.hs dest=~/.xmonad/xmonad.hs backup=yes
  register: xmonad_config

- name: Copy XMonad startup hook
  copy: src=startup-hook dest=~/.xmonad/startup-hook backup=yes mode=755

- name: Restart XMonad if config changed and XMonad is running
  shell: xmonad --restart
  when: lookup('env', 'DESKTOP_SESSION').find('xmonad') != -1 and xmonad_config|changed

- name: Recompile XMonad if config changed and xmonad is not running
  shell: xmonad --recompile
  when: lookup('env', 'DESKTOP_SESSION').find('xmonad') == -1 and xmonad_config|changed
