- name: Add signing key for Joonas Javanainen XMonad backports PPA
  apt_key: url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x62F9B6120B20AE72 state=present
  sudo: yes

- name: Add PPA for Joonas Javanainen XMonad backports
  apt_repository: repo='ppa:gekkio/xmonad' update_cache=yes state=present
  sudo: yes

- name: Install XMonad
  apt: pkg=xmonad update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Install ghc libraries required for configuring XMonad
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800
  with_items:
    - libghc-xmonad-dev
    - libghc-xmonad-contrib-dev
  sudo: yes

- name: Install gnome-panel
  apt: pkg=gnome-panel update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Install dependencies for Rofi
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800
  with_items:
    - autoconf
    - libxinerama-dev
    - libxft-dev
    - libpango1.0-dev
    - libx11-dev
  sudo: yes
    
- name: Get Rofi source code
  git: repo=https://github.com/DaveDavenport/rofi.git depth=1 accept_hostkey=True dest=~/software/rofi
  register: rofi_checkout

- name: Install Rofi
  shell: cd ~/software/rofi && autoreconf -i && mkdir -p build && cd build && ../configure --prefix=$HOME/local_packages/ --disable-i3support && make && make install
  when: rofi_checkout|changed

- name: Create Xresources.d if it does not exist
  shell: mkdir ~/Xresources.d creates=~/Xresources.d

- name: Copy Rofi config
  file: src={{ role_path }}/files/rofi dest=~/Xresources.d/rofi state=link
  register: rofi_config

- name: Include rofi config in ~/.Xresources
  lineinfile: dest=~/.Xresources line='#include "Xresources.d/rofi"' create=yes state=present

- name: Restart rofi if config changed
  shell: kill $(pgrep rofi) ; rofi -key-window mod4+s &
  when: rofi_config|changed

- name: Create directory to hold XMonad config
  command: mkdir ~/.xmonad creates=~/.xmonad

- name: Symlink XMonad personal config
  file: src={{ role_path }}/files/xmonad.hs dest=~/.xmonad/xmonad.hs state=link
  register: xmonad_config

- name: Symlink XMonad startup hook
  file: src={{ role_path }}/files/startup-hook dest=~/.xmonad/startup-hook state=link

- name: Symlink script to invoke org-capture
  file: src={{ role_path }}/files/org-capture dest=~/.xmonad/org-capture state=link

- name: Symlink GTK 2 config
  file: src={{ role_path }}/files/.gtkrc-2.0 dest=~/.gtkrc-2.0 state=link

- name: Create directory to hold GTK 3 config
  command: mkdir -p ~/.config/gtk-3.0 creates=~/.config/gtk-3.0

- name: Symlink GTK 3 config
  file: src={{ role_path }}/files/gtk-3.0-settings.ini dest=~/.config/gtk-3.0/settings.ini state=link

- name: Restart XMonad if config changed and XMonad is running
  shell: xmonad --restart
  when: lookup('env', 'DESKTOP_SESSION').find('xmonad') != -1 and xmonad_config|changed

- name: Recompile XMonad if config changed and xmonad is not running
  shell: xmonad --recompile
  when: lookup('env', 'DESKTOP_SESSION').find('xmonad') == -1 and xmonad_config|changed

- name: Add xmonad icons for unity greeter
  copy: src=xmonad-icon.png dest=/usr/share/unity-greeter/custom_xmonad_badge.png
  sudo: yes

- name: Add xmonad icons for unity greeter
  copy: src=xmonad-icon.png dest=/usr/share/unity-greeter/custom_gnome-xmonad_badge.png
  sudo: yes
