- name: Install XMonad
  apt: pkg=xmonad update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Install ghc libraries required for configuring XMonad
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800
  with_items:
    - libghc-xmonad-dev
    - libghc-xmonad-contrib-dev
  sudo: yes

- name: Install gnome-panel
  apt: pkg=gnome-panel update_cache=yes cache_valid_time=604800
  sudo: yes

- name: Install dependencies for Rofi
  apt: pkg={{ item }} update_cache=yes cache_valid_time=604800
  with_items:
    - libxinerama-dev
    - libxft-dev
    - libpango1.0-dev
    - libx11-dev

- name: Get Rofi release 0.15.4
  get_url: url=https://github.com/DaveDavenport/rofi/releases/download/0.15.4/rofi-0.15.4.tar.gz dest=~/compressed/rofi-0.15.4.tar.gz

- name: Extract Rofi source code
  unarchive: src=~/compressed/rofi-0.15.4.tar.gz dest=~/software/ creates=~/software/rofi-0.15.4

- name: Install Rofi
  shell: cd ~/software/rofi-0.15.4 && ./configure --prefix=$HOME/local_packages/ --disable-i3support && make && make install creates=~/local_packages/bin/rofi

- name: Create directory to hold XMonad config
  command: mkdir ~/.xmonad creates=~/.xmonad

- name: Copy XMonad personal config
  copy: src=xmonad.hs dest=~/.xmonad/xmonad.hs backup=yes
  register: xmonad_config

- name: Copy XMonad startup hook
  copy: src=startup-hook dest=~/.xmonad/startup-hook backup=yes mode=755

- name: Restart XMonad if config changed and XMonad is running
  shell: xmonad --restart
  when: lookup('env', 'DESKTOP_SESSION').find('xmonad') != -1 and xmonad_config|changed

- name: Recompile XMonad if config changed and xmonad is not running
  shell: xmonad --recompile
  when: lookup('env', 'DESKTOP_SESSION').find('xmonad') == -1 and xmonad_config|changed
